apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  annotations:
    hcapActive: "false"
  labels:
    promoter.argoproj.io/commit-status: hcap
  name: hcap
  namespace: helm-guestbook-promotion
spec:
  description: HCAP check for production
  gitRepositoryRef:
    name: github-argocd-example-apps
  name: hcap
  phase: success
  sha: 8db5b1bbd9138090162b94f64880d250a6c8d152
  url: https://example.com
