apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  annotations:
    hcapActive: "false"
  labels:
    promoter.argoproj.io/commit-status: hcap
  name: hcap
  namespace: helm-guestbook-promotion
spec:
  description: HCAP check for production
  gitRepositoryRef:
    name: github-argocd-example-apps
  name: hcap
  phase: pending
  sha: 22b308906b51ba38a22d0beb1bded8ed902322eb
  url: https://example.com
