apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  annotations:
    hcapActive: "false"
  labels:
    promoter.argoproj.io/commit-status: hcap
  name: hcap
  namespace: helm-guestbook-promotion
spec:
  description: HCAP check for production
  gitRepositoryRef:
    name: github-argocd-example-apps
  name: hcap
  phase: success
  sha: b4cc77942f02daa9412b7f0585febb57d6f26c96
  url: https://example.com
