apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    promoter.argoproj.io/commit-status: integration-tests-prod
  name: integration-tests-prod
  namespace: helm-guestbook-promotion
spec:
  description: Integration test check for production
  gitRepositoryRef:
    name: github-argocd-example-apps
  name: integration-tests-prod
  phase: success
  sha: b4cc77942f02daa9412b7f0585febb57d6f26c96
  url: https://example.com
