apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    promoter.argoproj.io/commit-status: integration-tests-prod
  name: integration-tests-prod
  namespace: helm-guestbook-promotion
spec:
  description: Integration test check for production
  gitRepositoryRef:
    name: github-argocd-example-apps
  name: integration-tests-prod
  phase: success
  sha: 8db5b1bbd9138090162b94f64880d250a6c8d152
  url: https://example.com
