apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    promoter.argoproj.io/commit-status: integration-tests-prod
  name: integration-tests-prod
  namespace: helm-guestbook-promotion
spec:
  description: Integration test check for production
  gitRepositoryRef:
    name: github-argocd-example-apps
  name: integration-tests-prod
  phase: success
  sha: 9e9f2d5ef2f905c973f31a3d0010d817414d5297
  url: https://example.com
