apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    promoter.argoproj.io/commit-status: integration-tests-dev
  name: integration-tests-dev
  namespace: helm-guestbook-promotion
spec:
  description: Integration test check for development
  gitRepositoryRef:
    name: github-argocd-example-apps
  name: integration-tests-dev
  phase: success
  sha: 7d82e17b82fca430f66815ab4c2b692264a5afe4
  url: https://example.com
