apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: prod-helm-guestbook
  name: prod-helm-guestbook
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: helm-guestbook
    release: prod-helm-guestbook
  type: ClusterIP
