apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: helm-guestbook-demo
  name: helm-guestbook-demo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: helm-guestbook
    release: helm-guestbook-demo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: helm-guestbook-demo
  name: helm-guestbook-demo
spec:
  replicas: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: helm-guestbook
      release: helm-guestbook-demo
  template:
    metadata:
      labels:
        app: helm-guestbook
        release: helm-guestbook-demo
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: helm-guestbook
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
